### ISSUE TITLE
Time formatting not respected 

### ISSUE THREAD

**Issue by PieMan2201** [matthewpipie/BlockScheduleHelperWWW#12]
With the 12-hour option off, the app still requests class start/end times in 12 hour time.

**Comment by matthewpipie** [comment]
It uses the system UI to manage picking times, and to display them in an input it uses the native behavior.  Doesnt happen for me.  It should be tied to what a regular <input type='time'> does on chrome (android) or safari (ios)

**Comment by PieMan2201** [comment]
Note the time format of the input prompts and the system time in the upper right corner. 
![screenshot_20160822-180238](https://cloud.githubusercontent.com/assets/9773351/17874671/d6b11a34-6892-11e6-8538-ad74310838cb.png)

**Comment by matthewpipie** [comment]
According to http://stackoverflow.com/questions/32184627/how-can-i-get-an-am-or-pm-indicator-to-display-with-the-html5-time-input-ele , the issue appears to be that chrome (which the app is secretly running on android) is displaying the input in 12hr because your language is set to US English.  There's not really a way around it, but I'll see if I can replace the time picker to make it consistant.
